### ISSUE TITLE
Reflect News prototype 5.0

### ISSUE THREAD

**Issue by ghost** [zikula-modules/News#13]
## Entity Options:
- [x] display on index
- [x] allow comments
- [x] no end date
- [x] weight -> see default sorting

### General Settings
- [x] enable Atrribution
- [x] enable Multi language
- [x] enable Events - unclear, for what this mod var was wished -> not needed, so deleted
- [x] show author
- [x] show date
### Categories
- [x] enable categories
- [x] enable category based permissions -> deleted

### Display Settings
- [x] default message sorting ->missunderstanding, has to be reimplemented
- [x] display pdf link

### Upload Settings
- [x] enable picture upload
- [x] image float on view page
- [x]  image float on display page

**Comment by Portugao** [comment]
Complete...
