### ISSUE TITLE
install News for ZK3 failed

### ISSUE THREAD

**Issue by rallek** [zikula-modules/News#139]
Error Code: -1Attempted to load class "MUNewsModule" from namespace "MU\NewsModule". Did you forget a "use" statement for another namespace?

![grafik](https://user-images.githubusercontent.com/935250/86391037-68a6c700-bc99-11ea-923b-feb48f39d3bd.png)

It is a fresh ZK3 install with the current news release

**Comment by Guite** [comment]
Fix in https://github.com/zikula/core/pull/4371

**Comment by Guite** [comment]
Closing here in favour of the core PR.
