### ISSUE TITLE
PDF Support

### ISSUE THREAD

**Issue by ghost** [zikula-modules/News#14]
dompdf causes error, so we have to look for another solution.
See: https://github.com/Guite/MostGenerator/issues/798

**Comment by Guite** [comment]
https://github.com/Guite/MostGenerator/issues/798 is solved. I successfully exported PDF files using a freshly generated 1.5 module. Please update and try again. Note you can/should now activate pdf support in the settings container of your model. The generator then creates all required stuff automatically so you do not need to customise it to get pdf functionality working.

**Comment by Portugao** [comment]
Oh Axel, that sounds really good. You are my hero. 😄

**Comment by rallek** [comment]
Will that work for my ShowRoomModule as well?

DomPDF not needed anymore?

**Comment by Guite** [comment]
DomPdf is still used; but it is now directly included using Composer instead of the old system plugin (which is not supported in Zikula 2 anyway).

**Comment by Portugao** [comment]
Seems to work; have to look at not finding images......

**Comment by Guite** [comment]
The basic functionality actually works in 1.2.0.

For example if I display an article using http://localhost/src/de/news/message/my-article I can open http://localhost/src/de/news/message/my-article.pdf

**Comment by Portugao** [comment]
Yes, the issue with images is already there....
So I close this and make another one.
