### ISSUE TITLE
News Module Switching Themes, Scribite Not Working

### ISSUE THREAD

**Issue by eledril** [zikula-modules/News#145]
I have done a clean install of Zikula 1.4.0 and installed News 3.1.1 along with Scribite 5.0.0 and PostCalendar 8.0.3. I have Andreas08 set as the theme for Administrators. I was able to move the Theme from my old installation (a modified FluidSolution) and I have gotten it pretty close to the way I had it before.
I am having some issues...
When I try to add an article in News, it switches from Andreas08 to Fluidsolution and the toolbars from Scribite don't work.
If I edit an article it doesn't switch and stays in Andreas08 but sometimes the toolbar from Scribite doesn't show up.
The same thing also appears to happen when I try to submit a new event in PostCalendar.
Is this an issue with Scribite? or with News? Any suggestions would be appreciated.

**Comment by eledril** [comment]
Anyone have any thoughts?

**Comment by eledril** [comment]
Anyone? It was suggested that I try using the Bootstrap Theme from 1.4.1 but I was receiving the same results.

**Comment by rallek** [comment]
Seems to be something special in your situation.

**Comment by eledril** [comment]
It would appear so. Any ideas what might be causing this?

**Comment by rallek** [comment]
do you have the same when using Andreas08 for the user theme as well (standard after installing)?

**Comment by eledril** [comment]
I had switched the Admin Theme to Bootstrap and that seems to have resolved the issue with the Admin Panel. I switched to the Admin and User Theme to Andreas08 (and cleared cache) an got the same issue. Then I tried switching both to Bootstrap and it looks like it's working. So it would appear that it's an issue with my FluidSolution Theme. I had pulled it out of the https://github.com/zikula/themes repository and modified it. I guess it's not completely compatible with 1.4.0. Any thoughts on how to improve the compatibility? 
Name	Fluidsolution
Type	Theme 3.0
Display name	Fluid Solution
Description	Fluid Solution OWD template
Directory	Fluidsolution
Version	2.1

**Comment by eledril** [comment]
Has anyone given any further thought to this issue? To provide an update. I have switched to a modified BlankTheme Theme which has been Bootstrapped. I thought that this would resolve the issue but it's still happening. I'm drawing a complete blank as to what could be causing this.
