### ISSUE TITLE
Submitting article results in a 500 error

### ISSUE THREAD

**Issue by robbrandt** [zikula-modules/News#148]
This is on 1.4.3 build 129

The article data is actually persisted to the database, but a 500 Internal Server Error shows instead of a results page.

This error message is displayed:

Invalid table-key [objectdata_attributes] retrieved

**Comment by robbrandt** [comment]
The above error happens on every News page until the submitted article is deleted from the database.

**Comment by robbrandt** [comment]
Seems to be related to using a category

**Comment by Guite** [comment]
Fixed in https://github.com/zikula/core/pull/3007

**Comment by robbrandt** [comment]
👍
