### ISSUE TITLE
News blocks are not showing up

### ISSUE THREAD

**Issue by rallek** [zikula-modules/News#151]
I tried the ``stories`` and ``storiesext`` block to bring to ``center`` but both are not shown.

It is the latest master of news and Zikula 1.4.4. 

Another block from a MOST-Module are working fine. Is it a news issue or is it a core issue because old (1.3.x) modules blocks do not show?

**Comment by rallek** [comment]
Inside blocks module also preview of the news blocks are empty. Is there anything I can do to see why?

**Comment by Guite** [comment]
Fixed in https://github.com/zikula/core/commit/fc2f13bdd0adab4ad7543997c7b737d90acf637b and https://github.com/zikula-modules/News/commit/be1adb13cd64391ae6c14a2fac8063f4127ebafe
