### ISSUE TITLE
Changing creator in news edit (Meta) not pssible anymore

### ISSUE THREAD

**Issue by rallek** [zikula-modules/News#152]
Trying to change the creator of a news leeds to a white screen with this message:
````
Beitragsautor
Einen neuen Autoren auswählen Error in DBUtil::executeSQL: SELECT uid AS "uid",uname AS "uname",email AS "email",pass AS "pass",passreminder AS "passreminder",activated AS "activated",approved_date AS "approved_date",approved_by AS "approved_by",user_regdate AS "user_regdate",lastlogin AS "lastlogin",theme AS "theme",tz AS "tz",locale AS "locale" FROM users AS tbl ORDER BY tbl.uname
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'passreminder' in 'field list'
````
Latest news with zikula 1.4.4 within a boostrap theme

**Comment by Guite** [comment]
Fixed in https://github.com/zikula/core/commit/3107de825fcb54d7f3e73ce91ef48b5c0b7b8da7

**Comment by rallek** [comment]
not done yet:
![grafik](https://cloud.githubusercontent.com/assets/935250/21467331/e0977e54-c9e9-11e6-9a2c-3c5209f03472.png)

**Comment by Guite** [comment]
Can't see the problem... ?

**Comment by rallek** [comment]
I can not say ok :-(

The image above is all I can see. Reopen or new issue?

**Comment by Guite** [comment]
You should describe the actual problem.

**Comment by rallek** [comment]
Edit a news and open Meta Data. Click at the pen for changing the creator. After clicking on that pen the above image is shown. I can choose the new creator but can not save it. 

Additional the layout for that operation looks strange. Nothing from my theme is showing up, only white screen with that wat the image is showing.

**Comment by Guite** [comment]
Fixed in 4808b7e2ed4b135dd1e7388e84d9b3ece917d1d2

@rallek the fix is already applied on your site.

**Comment by rallek** [comment]
But not working as expected. Now the modal is opening but if I change one to ``admin`` and save it the is no creator anymore. The field is empty.

**Comment by Guite** [comment]
Please create a new News issue for that.
