### ISSUE TITLE
More than three additional images

### ISSUE THREAD

**Issue by rallek** [zikula-modules/News#17]
currently we can define how many images are possible to upload. This is not possible anymore in the newest MUNews version.

My proposal is to have an additional entity with the images. There could be the copyright field and a short description.

Use the most function to define inside the module the size of the images so it will be shrinked during upload.

**Comment by Portugao** [comment]
Hi @gfr,
what about your part?

**Comment by Guite** [comment]
I just implemented this for 1.2.5. PR is coming...
