### ISSUE TITLE
after upgrade Zikula categories can not be selected anymore in edit

### ISSUE THREAD

**Issue by rallek** [zikula-modules/News#172]
I have upgraded zikula from 1.4.6 to 1.5.0. Also the latest News master is installed. Everything seems to work but category selection.

![grafik](https://user-images.githubusercontent.com/935250/29486144-9587c0f2-84df-11e7-9fed-f1ecb57cd9ba.png)

**Comment by Guite** [comment]
Fixed by https://github.com/zikula/core/pull/3777
