### ISSUE TITLE
modify menu

### ISSUE THREAD

**Issue by craigh** [zikula-modules/News#21]
![33094459-4434ab28-cece-11e7-958e-b25abdaea6f9](https://user-images.githubusercontent.com/350048/33144827-52e9899a-cf8c-11e7-9faf-4c8380a11ffb.png)

refs https://github.com/Guite/MostGenerator/issues/1169

change menu above to button group

**Comment by Portugao** [comment]
Fixed by https://github.com/Portugao/News/commit/d9eff6a78a5fdfe2791bd94b458389f3980843f2
