### ISSUE TITLE
Which fields should be visible in view?

### ISSUE THREAD

**Issue by ghost** [zikula-modules/News#22]
Have seen, that there are to many fields in the admin view template for my taste.
Which fields should be visible?
@Guite 
@craigh 
@rallek
Would like to improve that...

**Comment by craigh** [comment]
I assumed this was fixable by customizing the template...

**Comment by Guite** [comment]
It can also be configured in the model. Each field has a `displayType` property: https://modulestudio.de/documentation/c/87-GeneratorReference#field-display-type

**Comment by Portugao** [comment]
You're right. Sorry, my question is, if you think, it is helpful to reduce the cols in the view template.

**Comment by Portugao** [comment]
At the moment there are 20 cols, so one has to scroll to have access to the cols on the right side.

**Comment by Guite** [comment]
Proposal for a first step: keep state, title, maybe image upload 1, amount of views, author, approver, display on index, message language, allow comments, start date, no end date, end date

**Comment by craigh** [comment]
- state
 - title
 - display on index
 - combine no end date and end date
 - views

**Comment by Portugao** [comment]
Thx for your feedback.
