### ISSUE TITLE
Avatar label and file name should not be listed

### ISSUE THREAD

**Issue by rallek** [zikula-modules/News#223]
A small issue. It is not looking nice if the label (``Eigenes Bild``) and the file name (``gravatar.jpg``) are listed in the profile.

![grafik](https://user-images.githubusercontent.com/935250/33515394-ea4ac492-d762-11e7-8a22-11969b3dc4b0.png)

**Comment by Guite** [comment]
Looks like this belongs to the Profile module rather than News. Please resubmit in the correct tracker, thanks.
