### ISSUE TITLE
release and maintain a Core-2.0 version

### ISSUE THREAD

**Issue by craigh** [zikula-modules/News#26]
see https://stackoverflow.com/questions/50218840/with-which-module-can-i-create-or-blog-content-in-zikula-2-0-6/50221774#50221774

**Comment by Portugao** [comment]
Due to your comment at Stackoverflow I am tempted to close the ticket directly.

**Comment by Portugao** [comment]
A development version for core 2.0 is now available.
For helping please check and create tickets.
@craigh @rallek @Guite

**Comment by AlexL777** [comment]
Big Thanks for this good news and I will gladly use News 1.2.0 with me. Since I have to look at my Zikula project again or I have already installed Zikula 1.5, because it was advised to me. Hm ... let's see!

**Comment by Portugao** [comment]
Done.

**Comment by Guite** [comment]
:tada:

**Comment by AlexL777** [comment]
👍
