### ISSUE TITLE
No save button in edit template

### ISSUE THREAD

**Issue by ghost** [zikula-modules/News#28]

**Comment by Portugao** [comment]
Javascript error in both templates. Seems jQuery is not loaded...

**Comment by Guite** [comment]
> permalink field is below all other fields
Then it is not called in the edit template: Symfony adds all remaining fields at the end of the form by default.
So to place it somewhere else there should be something like `{{ form.slug }}`.

**Comment by Portugao** [comment]
Ok, the field is working now.

**Comment by Guite** [comment]
Please commit into the 1.1.0 branch and merge into 1.2.0 afterwards.

**Comment by Portugao** [comment]
Fixed by https://github.com/Portugao/News/commit/b6f522a83581add603a361b574157014f97aaa35
