### ISSUE TITLE
DefaultSortingField setting - no correct effect on view template

### ISSUE THREAD

**Issue by ghost** [zikula-modules/News#33]
The code in the controller helper worked in 1.5.x and does not work in 2.0.x.
No idea what causes this error.

Strange thing:
Overwriting the processViewTemplate method in the ControllerHelper.php has no effect under Zikula 2.0.x.

**Comment by Guite** [comment]
Not really... overriding is a functionality of object orientation. The Zikula core version is not relevant for that.

**Comment by Guite** [comment]
Actually it should be `ControllerHelper.php` instead of `Controller.php` - maybe you are editing an incorrectly named file?

**Comment by Portugao** [comment]
I updated my description. I worked on the ControllerHelper.php and it seems, the overriding has no effect.
Very strange.

**Comment by Portugao** [comment]
Have to reopen with new AbstractControllerHepler.php, because the sorting does not work again.

**Comment by Portugao** [comment]
Thx for your help, Axel; please see #36
