### ISSUE TITLE
No images found in generated PDF

### ISSUE THREAD

**Issue by ghost** [zikula-modules/News#34]

**Comment by Guite** [comment]
Maybe this needs to be enhanced https://github.com/Portugao/News/blob/1.2.0/MU/NewsModule/Helper/Base/AbstractViewHelper.php#L268-L269

**Comment by Portugao** [comment]
I think this code causes the problem:
```
        $output = str_replace('img src="/', 'img src="' . $this->request->server->get('DOCUMENT_ROOT') . '/', $output);
```
because the path does not lead to the picture....
