### ISSUE TITLE
sort and sortdir by mod var has no effect

### ISSUE THREAD

**Issue by ghost** [zikula-modules/News#36]
The sort and sortdir gets an overriding in the processViewActionParameters method.
So the overriding of the determine DefaultSortingFiled has no effect:
See https://github.com/Guite/MostGenerator/issues/1186
I can overrite the process method, but that is not very good, I think.

**Comment by Portugao** [comment]
At the end of the processViewActionParameters I have
sort: workflowState
sortdir: ASC

**Comment by Guite** [comment]
check the values directly after `list ($sort, $sortdir) = $this->determineDefaultViewSorting($objectType);`

**Comment by Portugao** [comment]
startDate, asc
entsprechend der Einstellung

**Comment by Portugao** [comment]
check after
```
        $sort = $sortableColumns->getSortColumn()->getName();
        $sortdir = $sortableColumns->getSortDirection();
        $sortableColumns->setAdditionalUrlParameters($urlParameters);
```
workflowState, ASC

**Comment by Guite** [comment]
Yeah the problem is basically that your sort column has no fitting table column. Going to fix it.

**Comment by Portugao** [comment]
Thx, that works. Great.
