### ISSUE TITLE
No update message on display

### ISSUE THREAD

**Issue by ghost** [zikula-modules/News#38]
We need no message for display; sending because of access counter.

**Comment by Guite** [comment]
Also at the moment there is only a link to the display page at the view page if a message has a body text. So if an article has no body text it's counter won't ever be increased. Thus, the display/detail link should always be visible I think.

**Comment by Portugao** [comment]
Seems not to be trivial to check, which field was updated....

**Comment by Guite** [comment]
You could enable `loggable` for versioning and change recording, but this seems overkill for a news module.

**Comment by Portugao** [comment]
Seems not to work...
