### ISSUE TITLE
Upgrade is missing

### ISSUE THREAD

**Issue by rallek** [zikula-modules/News#41]
I would like to see an upgrade procedure for news. After upgrade the core I do see the module in extensions as follow:
![grafik](https://user-images.githubusercontent.com/935250/46203607-9d465b80-c31a-11e8-9b7b-08bf39916d1d.png)

I do have a test case where I can support upgrade testing (like I did for ContentModule)

I hope @gfr is finalising the image inclusion so an upgrade becomes possible.

**Comment by Portugao** [comment]
Not sure, this is an issue of the News Module.....

**Comment by Portugao** [comment]
ping @Guite

**Comment by Guite** [comment]
To let the core detect that MUNewsModule is the successor of the old News module you need to add `News` to the `oldNames` array at https://github.com/Portugao/News/blob/newmaster/MU/NewsModule/composer.json#L39-L41

**Comment by Portugao** [comment]
I do not understand completely, @Guite .
From which version to which version you have updraded, @rallek ?

**Comment by Portugao** [comment]
I'm not sure, that I have understand your problem, @rallek . News is the MU/NewsModule and NewsPublisher is the old News module, right?

**Comment by rallek** [comment]
Exactly. The old NewsModule should be upgraded to yours

**Comment by Portugao** [comment]
Opinions, @Guite , @craigh , @gfr?

**Comment by craigh** [comment]
This was my position from the start. The old news module should have an upgrade path

**Comment by Portugao** [comment]
Any ideas how to implement, @craigh ?

**Comment by Guite** [comment]
The basic approach is quite simple: read all articles, loop over them, create new ones, copy images.

Examples for similar upgrades:

- [Formicula](https://github.com/zikula-modules/Formicula/blob/master/FormiculaModuleInstaller.php#L100)
- [Content](https://github.com/zikula-modules/Content/blob/master/src/modules/Zikula/ContentModule/ContentModuleInstaller.php#L44)

**Comment by Guite** [comment]
@Krator just added a migration from the old News module to the installer https://github.com/zikula-modules/News/pull/48

**Comment by paustian** [comment]
I have created a feature inside the new news module that imports news. However, it does not handle images right now. @rallek do you have a test case where images are included. I would be happy to try to add that. 
I had to make changes to two files. MessageController.php and LinkContainer.php. I think I did it in a way that is MOST approved. What is the best way to get them into News?

**Comment by Guite** [comment]
Create a fork of this repository, commit into this fork and create a pull request afterwards.

Do I understand correctly that your new feature replaces the code from #48 ?

**Comment by rallek** [comment]
@paustian yes, test case is available. I am not at home for some weeks. The internet is not good here. It will take some days to check if the test case is still up and running.

**Comment by Guite** [comment]
This is now done.
