### ISSUE TITLE
Show all categories

### ISSUE THREAD

**Issue by KratorD** [zikula-modules/News#47]
News 1.2.1
ZK 2.0.12

I only can see the categories that are folders. I cant see leaf categories. I hope I can categorize by leafs too. is it possible?

Thanks.

**Comment by Guite** [comment]
Examples? Screenshots?

**Comment by KratorD** [comment]
![imagen](https://user-images.githubusercontent.com/5812569/54198976-13550e00-44c8-11e9-8d04-cf64bf190614.png)
![imagen](https://user-images.githubusercontent.com/5812569/54199140-7646a500-44c8-11e9-9285-b2a55a08e4aa.png)

**Comment by Guite** [comment]
Try overriding the `Helper/includeCategoriesEdit.html.twig` template and change
`{{ form_row(form.categories) }}`
to
`{{ form_row(form.categories, {direct: false}) }}`

**Comment by KratorD** [comment]
Hi @Guite .
Sorry for delay. I tried the change, but the same thing appears, don't work.
Thanks.

**Comment by Guite** [comment]
Then you need to add `'direct' => false,` here: https://github.com/zikula-modules/News/blob/master/MU/NewsModule/Form/Type/Base/AbstractMessageType.php#L420 I tested that and it works fine.
No idea why it does not work from the template though.

**Comment by KratorD** [comment]
That's works, thanks
