### ISSUE TITLE
New Feature: Integration with comments extensions

### ISSUE THREAD

**Issue by KratorD** [zikula-modules/News#51]
This feature was available in old News module. 
If you have a "comment" extension installed in your zikula (Comments, EZComments), the entity "news" will contain a new calculated field in the template -> "commentcount", with the number of comments of the new.
So, in you template, you could use it for show the # of comments.

Thanks.

**Comment by craigh** [comment]
News should not "mix" with other modules in my opinion. These types of Views should be accomodated through Display Hooks. In the "old" way, the News module literally had something like `if isAvailable(NewsModule) { show commentCount}` etc. This is bad design. It should simply display all Hooks as appropriate. The **comments** module should accomodate this request.

**Comment by KratorD** [comment]
Well, the code of old module was `if isAvailable(commentModule){addTemplatevariable commentCount to the new}`. So, you always have the number of comments for use in News templates, because, usually, you want show something how 

> contributed by X on date, x comments, read more...

And use `commentsCount` in blocks too.
Is it possible this with a Hook in "comments"? Maybe an Event on News? You are the experts, i get lost

**Comment by Guite** [comment]
Closing as this seems to be fixed by EZComments (two different provider areas; see the issue linked above)
