### ISSUE TITLE
Extend limit the characters

### ISSUE THREAD

**Issue by KratorD** [zikula-modules/News#52]
Start text: 10.000 characters
Main text: 20.000 characters.

I think that, at least, the Main text could be enhancement to "unlimited" characters. The characters are limited to html code, and 20.000 characters can be full easily, especially if you are using "MediaModule" that contain extensive URL/code. (for example: `https://www.heroesofmightandmagic.es/portal/media/cache/resolve/zkroot/rc/4nk85xiP/fichdata/cmfcmf-media-module/media/5be6c5f8d539dbe2f2ecc2c3776c621e9ad9d5d3.jpg?filters%5Bthumbnail%5D%5Bsize%5D%5B0%5D=200&amp;filters%5Bthumbnail%5D%5Bsize%5D%5B1%5D=150&amp;filters%5Bthumbnail%5D%5Bmode%5D=outbound&amp;filters%5Bcmfcmfmediamodule.custom_image_filter%5D%5Bfile%5D=fichdata/cmfcmf-media-module/media/5be6c5f8d539dbe2f2ecc2c3776c621e9ad9d5d3.jpg&amp;filters%5Bcmfcmfmediamodule.custom_image_filter%5D%5Bwidth%5D=200&amp;filters%5Bcmfcmfmediamodule.custom_image_filter%5D%5Bheight%5D=150&amp;filters%5Bcmfcmfmediamodule.custom_image_filter%5D%5Bmode%5D=outbound&amp;filters%5Bcmfcmfmediamodule.custom_image_filter%5D%5Boptimize%5D=1` ( more than 700 characters)

Thanks.

**Comment by Guite** [comment]
I increased startText to 20000 (twice as big) and mainText to 100000 (five times as big) characters in the model  (commit 951dc36f3866c93dc125c415cbacdf9783f458ec).
The new lengths will be applied as part of next regeneration which I am going to do asap.
Closing.
